arrowParens: "always"
bracketSpacing: true
bracketSameLine: false
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
insertPragma: false
printWidth: 140
proseWrap: preserve
quoteProps: "as-needed"
requirePragma: false
semi: true
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false
singleAttributePerLine: false
embeddedLanguageFormatting: "auto"
jsxSingleQuote: false
