name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-3.5-turbo" # optional
          openai_temperature: 0.5 # optional
          openai_max_tokens: 4096 # optional
          mode: files # files or patch
          language: ja # optional, default is 'en'
          custom_prompt: "" # optional
