name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: dokimiki/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md, **/*.env*, **/*.lockb, **/*.(yml|yaml), **/*.(jpg|jpeg|png|svg|ico|gif|webp)" # Optional: exclude patterns separated by commas
